---
server:
  port: 8080
  contextPath: /cos
---
spring:
  profiles: default
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/cosmetic_online_store
    username: root
    password: thdb010708
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

something:
    clientId: 162843850906748
    clientSecret: 8bc3a3a6abf3b46daf3c708de2ea3997