package com.cos.entities;
// Generated Apr 21, 2017 6:33:01 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "cosmetic_online_store")
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private User user;
	private String totalPrice;
	private String note;
	private Set<Selectedproduct> selectedproducts = new HashSet<Selectedproduct>(0);

	public Cart() {
	}

	public Cart(User user, String totalPrice, String note, Set<Selectedproduct> selectedproducts) {
		this.user = user;
		this.totalPrice = totalPrice;
		this.note = note;
		this.selectedproducts = selectedproducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cartId", unique = true, nullable = false)
	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "totalPrice", length = 20)
	public String getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(String totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "carts")
	public Set<Selectedproduct> getSelectedproducts() {
		return this.selectedproducts;
	}

	public void setSelectedproducts(Set<Selectedproduct> selectedproducts) {
		this.selectedproducts = selectedproducts;
	}

}
