package com.cos.entities;
// Generated Apr 21, 2017 6:33:01 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "cosmetic_online_store")
public class Image implements java.io.Serializable {

	private Integer imageId;
	private Product product;
	private String link;

	public Image() {
	}

	public Image(Product product, String link) {
		this.product = product;
		this.link = link;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "imageId", unique = true, nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "link", length = 65535)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
