package com.cos.entities;
// Generated Jun 23, 2017 6:43:50 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "cosmetic_online_store")
public class News implements java.io.Serializable {

	private Integer newId;
	private User user;
	private String header;
	private String content;
	private Date addedDate;
	private Date addedTime;

	public News() {
	}

	public News(User user, String header, String content, Date addedDate, Date addedTime) {
		this.user = user;
		this.header = header;
		this.content = content;
		this.addedDate = addedDate;
		this.addedTime = addedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "newId", unique = true, nullable = false)
	public Integer getNewId() {
		return this.newId;
	}

	public void setNewId(Integer newId) {
		this.newId = newId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "header", length = 65535)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "addedDate", length = 10)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "addedTime", length = 8)
	public Date getAddedTime() {
		return this.addedTime;
	}

	public void setAddedTime(Date addedTime) {
		this.addedTime = addedTime;
	}

}
