package com.cos.entities;
// Generated Apr 21, 2017 6:33:01 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Selectedproduct generated by hbm2java
 */
@Entity
@Table(name = "selectedproduct", catalog = "cosmetic_online_store")
public class Selectedproduct implements java.io.Serializable {

	private Integer selectedId;
	private Product product;
	private Integer quantity;
	private Set<Cart> carts = new HashSet<Cart>(0);

	public Selectedproduct() {
	}

	public Selectedproduct(Product product, Integer quantity, Set<Cart> carts) {
		this.product = product;
		this.quantity = quantity;
		this.carts = carts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "selectedId", unique = true, nullable = false)
	public Integer getSelectedId() {
		return this.selectedId;
	}

	public void setSelectedId(Integer selectedId) {
		this.selectedId = selectedId;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "selectedproductcart", catalog = "cosmetic_online_store", joinColumns = {
			@JoinColumn(name = "selectedId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "cartId", nullable = false, updatable = false) })
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

}
