package com.cos.entities;
// Generated Jun 13, 2017 6:54:30 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Selectedproduct generated by hbm2java
 */
@Entity
@Table(name = "selectedproduct", catalog = "cosmetic_online_store")
public class SelectedProduct implements java.io.Serializable {

	private Integer selectedId;
	private Cart cart;
	private Product product;
	private User user;
	private Integer quantity;
	private Boolean checkOut;

	public SelectedProduct() {
	}

	public SelectedProduct(Cart cart, Product product, User user, Integer quantity, Boolean checkOut) {
		this.cart = cart;
		this.product = product;
		this.user = user;
		this.quantity = quantity;
		this.checkOut = checkOut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "selectedId", unique = true, nullable = false)
	public Integer getSelectedId() {
		return this.selectedId;
	}

	public void setSelectedId(Integer selectedId) {
		this.selectedId = selectedId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cartId")
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "checkOut")
	public Boolean getCheckOut() {
		if (checkOut == null) {
			setCheckOut(false);
		}
		return this.checkOut;
	}

	public void setCheckOut(Boolean checkOut) {
		this.checkOut = checkOut;
	}

}
