package com.cos.entities;
// Generated Jun 13, 2017 6:54:30 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "cosmetic_online_store")
public class User implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private String email;
	private String phone;
	private Integer roleId;
	private List<SelectedProduct> selectedproducts = new ArrayList<SelectedProduct>();
	private List<News> newses = new ArrayList<News>();
	private List<Videos> videoses = new ArrayList<Videos>();

	public User() {
	}

	public User(String username, String password, String firstName, String lastName, String address, String city,
			String email, String phone, Integer roleId, List<SelectedProduct> selectedproducts, List<News> newses,
			List<Videos> videoses) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.city = city;
		this.email = email;
		this.phone = phone;
		this.roleId = roleId;
		this.selectedproducts = selectedproducts;
		this.newses = newses;
		this.videoses = videoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstName")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "roleId")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<SelectedProduct> getSelectedproducts() {
		return this.selectedproducts;
	}

	public void setSelectedproducts(List<SelectedProduct> selectedproducts) {
		this.selectedproducts = selectedproducts;
	}
	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<News> getNewses() {
		return this.newses;
	}

	public void setNewses(List<News> newses) {
		this.newses = newses;
	}
	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<Videos> getVideoses() {
		return this.videoses;
	}

	public void setVideoses(List<Videos> videoses) {
		this.videoses = videoses;
	}

}
